esphome:
  name: rackfan

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  # MAC: 3c:61:05:15:6b:30
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Manual IP only assigned so we can get logs by IP instead of resolving rackfan.local
  manual_ip:
    static_ip: !secret manual_ip_static_ip
    gateway: !secret manual_ip_gateway
    subnet: 255.255.255.0
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rackfan Fallback Hotspot"
    password: !secret ap_password

captive_portal:

i2c:
  #sda: GPIOXX # default: 42 GPIO21
  #scl: GPIOXX # default: 39 GPIO22
  scan: false
  id: bus_a

sensor:
  - platform: pulse_counter
    pin: GPIO13
    name: PWM Fan 0 RPM
    id: fan_pulse0
    unit_of_measurement: 'RPM'
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 3s
    filters:
      - multiply: 0.5
  - platform: pulse_counter
    pin: GPIO14
    name: PWM Fan 1 RPM
    id: fan_pulse1
    unit_of_measurement: 'RPM'
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 3s
    filters:
      - multiply: 0.5
  - platform: tmp102
    name: "Server Rack Temperature"
    update_interval: 15s

output:
  - platform: ledc
    pin: GPIO9
    frequency: 10000 Hz
    id: fanhub_pwm0
  - platform: ledc
    pin: GPIO27
    frequency: 10000 Hz
    id: fanhub_pwm1

fan:
  - platform: speed
    output: fanhub_pwm0
    name: "PWM Fan 0"
    restore_mode: ALWAYS_ON
  - platform: speed
    output: fanhub_pwm1
    name: "PWM Fan 1"
    restore_mode: ALWAYS_ON

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO32
    num_leds: 38
    rgb_order: GRB
    name: "Rack FastLED Strips"
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          transition_length: 500ms
          update_interval: 2s
      - pulse:
          name: "Asymmetrical Pulse"
          transition_length:
            on_length: 1s
            off_length: 500ms
          update_interval: 1.5s
      - addressable_rainbow:
          name: Default rainbow
      - addressable_rainbow:
          name: Wide rainbow
          speed: 5
          width: 100
      - addressable_color_wipe:
            name: Default color wipe
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 5
              gradient: true
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
      - addressable_scan:
          move_interval: 25ms
          scan_width: 3
      - addressable_fireworks:
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
      - addressable_twinkle:
          twinkle_probability: 15%
          progress_interval: 4ms
      - addressable_random_twinkle:
          twinkle_probability: 15%
          progress_interval: 32ms
